#!/usr/bin/env python3
"""
schemas.py — Frozen dataclasses for Competitive Intelligence Layer.

All dataclasses are frozen=True — immutable after construction.
READ-ONLY layer: extracts patterns from public data, NEVER copies content.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict

# ── Visual styles ────────────────────────────────────────────────────────────

VISUAL_STYLES: frozenset[str] = frozenset({
    "luxury_dark",
    "minimal_clean",
    "warm_lifestyle",
    "cinematic_commercial",
    "tech_premium",
})

# ── Hook types ───────────────────────────────────────────────────────────────

HOOK_TYPES: frozenset[str] = frozenset({
    "hook_first",        # attention-grabbing first line
    "storytelling",      # narrative opening
    "question_led",      # starts with a question
    "stat_claim",        # starts with a statistic or claim
    "curiosity_gap",     # teases without revealing
    "pain_point",        # addresses a problem
    "transformation",    # before/after framing
    "urgency_scarcity",  # limited time/stock framing
})

# ── CTA types ────────────────────────────────────────────────────────────────

CTA_TYPES: frozenset[str] = frozenset({
    "link_in_bio",
    "comment_keyword",     # "comment X to get the link"
    "swipe_up",
    "shop_now",
    "save_for_later",
    "tag_friend",
    "follow_for_more",
    "soft_mention",        # subtle reference, no direct ask
    "none",                # no CTA detected
})

# ── Posting frequency labels ─────────────────────────────────────────────────

FREQUENCY_LABELS: frozenset[str] = frozenset({
    "daily",
    "multi_daily",     # 2+ posts per day
    "weekly_few",      # 2-4 per week
    "weekly",           # ~1 per week
    "sparse",           # less than weekly
    "irregular",
})


# ── Schemas ──────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class CompetitorAccount:
    """
    A tracked competitor social media account.

    Fields:
        account_id:     unique identifier
        username:        social handle (e.g., @brandname)
        platform:        instagram | tiktok | twitter | pinterest | youtube
        niche:           product/market niche
        tags:            categorization tags
        added_at:        ISO UTC when added to registry
        active:          whether this account is currently being tracked
    """
    account_id: str
    username:   str
    platform:   str
    niche:      str
    tags:       tuple[str, ...] = ()
    added_at:   str             = ""
    active:     bool            = True

    def to_dict(self) -> dict:
        d = asdict(self)
        d["tags"] = list(self.tags)
        return d


@dataclass(frozen=True)
class PublicPostFingerprint:
    """
    Pattern fingerprint of a single public post — STRUCTURE, not content.

    Never stores: raw text, images, or identifiable content.
    Only stores: structural patterns, metrics, and style classifications.
    """
    fingerprint_id: str       # SHA256 hash of account + post URL
    account_id:     str
    platform:       str
    collected_at:   str       # ISO UTC

    # Structural patterns (NOT content)
    hook_type:      str       # one of HOOK_TYPES (or "unknown")
    cta_type:        str       # one of CTA_TYPES (or "none")
    sentence_count:  int
    avg_sentence_length: float
    has_emoji:       bool
    emoji_count:     int
    has_hashtags:    bool
    hashtag_count:   int
    has_question:    bool

    # Visual pattern fingerprint (NOT images, NOT pixel data)
    visual_style:    str       # one of VISUAL_STYLES (or "unknown")
    color_palette:   str       # dominant color scheme label (e.g., "dark_monochrome")
    composition:     str       # framing label (e.g., "center_product", "lifestyle_wide")
    text_overlay:    bool      # whether image has text overlay

    # Engagement metrics (public, estimated)
    likes_est:       int       = 0
    comments_est:    int       = 0
    shares_est:      int       = 0
    views_est:       int       = 0
    engagement_rate: float     = 0.0   # computed: (likes+comments)/estimated_followers

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class CompetitorInsight:
    """
    Aggregated insight about a competitor account.

    Generated by insight_engine from multiple PublicPostFingerprints.
    """
    account_id:       str
    username:         str
    platform:         str
    analyzed_at:      str       # ISO UTC

    # Aggregated metrics
    avg_engagement_rate: float
    estimated_posts_per_week: float
    frequency_label:  str       # one of FREQUENCY_LABELS

    # Pattern distributions
    dominant_style:   str       # most common VISUAL_STYLE
    style_distribution: dict[str, float]   # style → percentage

    dominant_hook:    str       # most common HOOK_TYPE
    hook_distribution: dict[str, float]    # hook → percentage

    dominant_cta:     str       # most common CTA_TYPE
    cta_distribution:   dict[str, float]  # CTA → percentage

    # Viral signals
    viral_score:      float     # 0.0–1.0 composite
    top_patterns:     tuple[str, ...]  # human-readable pattern descriptions

    # Read-only — for feeding Visual Intelligence
    recommended_archetype_tags: tuple[str, ...]  # e.g., ("luxury_dark", "hook_first")

    def to_dict(self) -> dict:
        d = asdict(self)
        d["top_patterns"] = list(self.top_patterns)
        d["recommended_archetype_tags"] = list(self.recommended_archetype_tags)
        return d


@dataclass(frozen=True)
class TrendRank:
    """
    Ranked competitor trend entry — the output format from the plan.
    """
    account:         str
    style:           str
    engagement_rate: float
    viral_score:     float
    patterns:        tuple[str, ...]

    def to_dict(self) -> dict:
        return {
            "account":         self.account,
            "style":           self.style,
            "engagement_rate": self.engagement_rate,
            "viral_score":     self.viral_score,
            "patterns":        list(self.patterns),
        }


@dataclass(frozen=True)
class IntelligenceReport:
    """
    Complete competitive intelligence report.
    """
    generated_at:     str
    accounts_analyzed: int
    trends:           tuple[TrendRank, ...]
    global_insights:  tuple[str, ...]   # human-readable insights
    archetype_feeds:  tuple[str, ...]   # tags to feed into archetype engine

    def to_dict(self) -> dict:
        return {
            "generated_at":      self.generated_at,
            "accounts_analyzed": self.accounts_analyzed,
            "trends":            [t.to_dict() for t in self.trends],
            "global_insights":   list(self.global_insights),
            "archetype_feeds":   list(self.archetype_feeds),
        }
