#!/usr/bin/env python3
"""
schemas.py — Canonical types for the Visual Intelligence subsystem.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field, asdict
from typing import Optional


@dataclass(frozen=True)
class ImageEmbedding:
    """
    CLIP embedding for one generated image.
    Stored in FAISS + metadata store.
    """
    post_id:          str     # links to social post + revenue_layer
    product_id:       str     # ASIN
    platform:         str     # instagram | tiktok | telegram
    image_path:       str     # absolute path at time of encoding
    image_hash:       str     # sha256[:16] — dedup / cache key
    embedding_model:  str     # "ViT-B/32" | "histogram_fallback"
    encoded_at:       str     # ISO 8601 UTC
    # Performance fields — updated by performance_linker
    performance_score: float  = 0.0   # revenue / impressions (0.0 = not yet linked)
    clicks:            int    = 0
    conversions:       int    = 0
    revenue:           float  = 0.0
    performance_at:    str    = ""    # last performance update timestamp

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "ImageEmbedding":
        return cls(**{k: d.get(k, v) for k, v in cls.__dataclass_fields__.items()})


@dataclass(frozen=True)
class VisualArchetype:
    """
    A discovered visual style cluster.
    Generated by archetype_engine from FAISS embeddings.
    """
    archetype_id:       str     # "ARCHETYPE_{product_id}_{cluster_idx}"
    product_id:         str
    label:              str     # human-readable: "DARK_LUXURY_CINEMATIC_02"
    cluster_size:       int     # number of embeddings in cluster
    avg_performance:    float   # mean performance_score of cluster members
    centroid_summary:   str     # textual description for prompt injection
    top_post_ids:       tuple   # tuple[str, ...] — top performing posts in cluster
    created_at:         str

    def to_dict(self) -> dict:
        return {
            "archetype_id":    self.archetype_id,
            "product_id":      self.product_id,
            "label":           self.label,
            "cluster_size":    self.cluster_size,
            "avg_performance": round(self.avg_performance, 6),
            "centroid_summary": self.centroid_summary,
            "top_post_ids":    list(self.top_post_ids),
            "created_at":      self.created_at,
        }


@dataclass
class ArchetypeDirective:
    """
    Output of visual_optimizer — injected into Flow prompt.
    Bias strength: 0.0 = no bias, 1.0 = full determinism.
    """
    product_id:              str
    archetype_id:            str
    label:                   str
    prompt_injection:        str    # text to prepend to Flow prompt
    bias_strength:           float  # 0.0–1.0
    source:                  str    # "optimizer" | "random" | "fallback"
    created_at:              str
    soft_hint:               str = ""   # LEARNING mode: style hints (comma-separated)
    full_archetype_injection: str = ""  # OPTIMIZING mode: full formatted injection string

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def random(cls, product_id: str) -> "ArchetypeDirective":
        """No-bias directive when insufficient data."""
        return cls(
            product_id=product_id,
            archetype_id="",
            label="RANDOM_EXPLORATION",
            prompt_injection="",
            bias_strength=0.0,
            source="random",
            created_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        )
